/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.csse.ui;

import Appointment.AMain;
import Appointment.Add_Appointment;
import Appointment.Update_Appointment;
import Charges.CMain;
import Patient_Management.Approve_Drugs;
import Patient_Management.Check_History;
import Patient_Management.Diagnosis;
import Patient_Management.Doc_schedule;
import Patient_Management.Prescriptions;
import Patient_Management.Register_Patients;
import Payment_Fee.PMain;
import Schedule.SMain;
import code.notification;
import com.csse.validation.UsersValidation;
import pharmacy_lab.Add_drugs;
import pharmacy_lab.Drug_order;
import pharmacy_lab.Manage_Lab_Test;
import pharmacy_lab.Manage_Patient_Lab_test;
import pharmacy_lab.Order_Chemical;
import pharmacy_lab.Payment_Order;
import pharmacy_lab.Search_Patient_Lab_Test;
import pharmacy_lab.manage_chemical;
import pharmacy_lab.searchDrug;
import pharmacy_lab.searchLabTest;


/**
 *
 * @author Anuradha Sanjeewa
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        notification n = new notification();
        int num = n.countNoytification();
        String number = new Integer(num).toString();
        lblNumber.setText(number);

    }

     public MainMenu(String userName,String nic) {
        initComponents();
        lblUser.setText(userName);
        UsersValidation uv = new UsersValidation();
       // uv.userPermission(nic,jbtnUser,JMenu5);
       // uv.userPermission(nic, jbtnUser,jmRegister);
        //uv.userPermission(nic,jmAddUsers);
        uv.userPermission(nic, jmAddUsers, jmNewUser, jmEmpDtl, jmPatiemtManage, jmLabTest);
        System.out.println(nic);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblNumber = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmPatiemtManage = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jmNewUser = new javax.swing.JMenu();
        jmAddUsers = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jmLabTest = new javax.swing.JMenu();
        jMenu20 = new javax.swing.JMenu();
        jMenu21 = new javax.swing.JMenu();
        jMenu22 = new javax.swing.JMenu();
        jMenu23 = new javax.swing.JMenu();
        jMenu24 = new javax.swing.JMenu();
        jMenu25 = new javax.swing.JMenu();
        jmEmpDtl = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jmApointment = new javax.swing.JMenu();
        jMenu27 = new javax.swing.JMenu();
        jMenu30 = new javax.swing.JMenu();
        jMenu31 = new javax.swing.JMenu();
        jMenu32 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setSize(new java.awt.Dimension(850, 850));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("User");

        lblUser.setText("User");

        jLabel2.setText("Notification");

        lblNumber.setText("Number");
        lblNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNumberMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(lblNumber)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblNumber)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblUser)
                .addGap(184, 184, 184)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(797, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUser))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jDesktopPane1.setBackground(new java.awt.Color(153, 153, 153));
        jDesktopPane1.setAutoscrolls(true);
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(680, 550));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1336, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        jMenuBar1.setEnabled(false);
        jMenuBar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jMenuBar1KeyReleased(evt);
            }
        });

        jmPatiemtManage.setText("|Patient Manage|");

        jMenu11.setText("Register Patient");
        jMenu11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu11MouseClicked(evt);
            }
        });
        jmPatiemtManage.add(jMenu11);

        jMenu12.setText("Check History");
        jMenu12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu12MouseClicked(evt);
            }
        });
        jmPatiemtManage.add(jMenu12);

        jMenu13.setText("Diagnosis Details");
        jMenu13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu13MouseClicked(evt);
            }
        });
        jmPatiemtManage.add(jMenu13);

        jMenu14.setText("Prescriptions & Lab Investigations");
        jMenu14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu14MouseClicked(evt);
            }
        });
        jmPatiemtManage.add(jMenu14);

        jMenu15.setText("Cancel Appointment");
        jMenu15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu15MouseClicked(evt);
            }
        });
        jmPatiemtManage.add(jMenu15);

        jMenu16.setText("Approve Drugs");
        jMenu16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu16MouseClicked(evt);
            }
        });
        jmPatiemtManage.add(jMenu16);

        jMenuBar1.add(jmPatiemtManage);

        jMenu4.setText("|Pharmacy |");

        jMenu3.setText("Drug Manage");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu4.add(jMenu3);

        jMenu17.setText("Order Drug");
        jMenu17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu17MouseClicked(evt);
            }
        });
        jMenu4.add(jMenu17);

        jMenu18.setText("Search Drug");
        jMenu18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu18MouseClicked(evt);
            }
        });
        jMenu4.add(jMenu18);

        jMenu19.setText("Payment Orders");
        jMenu19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu19MouseClicked(evt);
            }
        });
        jMenu4.add(jMenu19);

        jMenuBar1.add(jMenu4);

        jmNewUser.setText("|New User|");
        jmNewUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmNewUserMouseClicked(evt);
            }
        });

        jmAddUsers.setText("Add Users");
        jmAddUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAddUsersMouseClicked(evt);
            }
        });
        jmNewUser.add(jmAddUsers);

        jMenu5.setText("Register Users");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jmNewUser.add(jMenu5);

        jMenuBar1.add(jmNewUser);

        jmLabTest.setText("|Lab Test| ");
        jmLabTest.setPreferredSize(new java.awt.Dimension(55, 22));

        jMenu20.setText("Manage Lab Test");
        jMenu20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu20MouseClicked(evt);
            }
        });
        jmLabTest.add(jMenu20);

        jMenu21.setText("Search Lab Test");
        jMenu21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu21MouseClicked(evt);
            }
        });
        jmLabTest.add(jMenu21);

        jMenu22.setText("Order Chemical");
        jMenu22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu22MouseClicked(evt);
            }
        });
        jmLabTest.add(jMenu22);

        jMenu23.setText("Manage Patient Lab Test");
        jMenu23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu23MouseClicked(evt);
            }
        });
        jmLabTest.add(jMenu23);

        jMenu24.setText("Search Patient Lab Test");
        jMenu24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu24MouseClicked(evt);
            }
        });
        jmLabTest.add(jMenu24);

        jMenu25.setText("Manage Chemical");
        jMenu25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu25MouseClicked(evt);
            }
        });
        jmLabTest.add(jMenu25);

        jMenuBar1.add(jmLabTest);

        jmEmpDtl.setText("|Employee Details|");

        jMenu8.setText("Salary");
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jmEmpDtl.add(jMenu8);

        jMenu9.setText("Leaves");
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu9MouseClicked(evt);
            }
        });
        jmEmpDtl.add(jMenu9);

        jMenu10.setText("Report");
        jMenu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu10MouseClicked(evt);
            }
        });
        jmEmpDtl.add(jMenu10);

        jMenuBar1.add(jmEmpDtl);

        jmApointment.setText("|Appointment|");
        jmApointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmApointmentMouseClicked(evt);
            }
        });

        jMenu27.setText("AppointmentMain");
        jMenu27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu27MouseClicked(evt);
            }
        });
        jmApointment.add(jMenu27);

        jMenu30.setText("Charges Main");
        jMenu30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu30MouseClicked(evt);
            }
        });
        jmApointment.add(jMenu30);

        jMenu31.setText("Payment Main");
        jMenu31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu31MouseClicked(evt);
            }
        });
        jmApointment.add(jMenu31);

        jMenu32.setText("ScheduleMain");
        jMenu32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu32MouseClicked(evt);
            }
        });
        jmApointment.add(jMenu32);

        jMenuBar1.add(jmApointment);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNumberMouseClicked

        notification n = new notification();
        n.getDetails();
    }//GEN-LAST:event_lblNumberMouseClicked

    private void jMenuBar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuBar1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1KeyReleased

    private void jMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MouseClicked
        jDesktopPane1.removeAll();
        EmpLeaves leaves = new EmpLeaves();
        jDesktopPane1.add(leaves);
        leaves.show();
    }//GEN-LAST:event_jMenu9MouseClicked

    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
        jDesktopPane1.removeAll();
        Salary salary = new Salary();
        jDesktopPane1.add(salary);
        salary.show();
    }//GEN-LAST:event_jMenu8MouseClicked

    private void jmNewUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmNewUserMouseClicked
//                jDesktopPane1.removeAll();
//                Register register = new Register();
//                jDesktopPane1.add(register);
//                register.show();
    }//GEN-LAST:event_jmNewUserMouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        jDesktopPane1.removeAll();
        Register register = new Register();
        jDesktopPane1.add(register);
        
        register.show();
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jmAddUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAddUsersMouseClicked

        jDesktopPane1.removeAll();
        Users users = new Users();
        jDesktopPane1.add(users);
        users.show();
        // register.setMaximum(true);
    }//GEN-LAST:event_jmAddUsersMouseClicked

    private void jMenu16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu16MouseClicked
        jDesktopPane1.removeAll();
        Approve_Drugs approveDrugs = new Approve_Drugs();
        jDesktopPane1.add(approveDrugs);
        approveDrugs.show();
    }//GEN-LAST:event_jMenu16MouseClicked

    private void jMenu15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu15MouseClicked
        jDesktopPane1.removeAll();
        Doc_schedule docSchedule = new Doc_schedule();
        jDesktopPane1.add(docSchedule);
        docSchedule.show();
    }//GEN-LAST:event_jMenu15MouseClicked

    private void jMenu14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu14MouseClicked
        jDesktopPane1.removeAll();
        Prescriptions prescriptions = new Prescriptions();
        jDesktopPane1.add(prescriptions);
        prescriptions.show();
    }//GEN-LAST:event_jMenu14MouseClicked

    private void jMenu13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu13MouseClicked
        jDesktopPane1.removeAll();
        Diagnosis diagnosis = new Diagnosis();
        jDesktopPane1.add(diagnosis);
        diagnosis.show();
    }//GEN-LAST:event_jMenu13MouseClicked

    private void jMenu12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu12MouseClicked
        jDesktopPane1.removeAll();
        Check_History checkHistory = new Check_History();
        jDesktopPane1.add(checkHistory);
        checkHistory.show();
    }//GEN-LAST:event_jMenu12MouseClicked

    private void jMenu11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu11MouseClicked
        jDesktopPane1.removeAll();
        Register_Patients registerPatients = new Register_Patients();
        jDesktopPane1.add(registerPatients);
        registerPatients.show();
    }//GEN-LAST:event_jMenu11MouseClicked

    private void jMenu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu10MouseClicked
        jDesktopPane1.removeAll();
        ScheduleReport scheduleReport = new ScheduleReport();
        jDesktopPane1.add(scheduleReport);
        scheduleReport.show();
    }//GEN-LAST:event_jMenu10MouseClicked

    private void jMenu20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu20MouseClicked
        jDesktopPane1.removeAll();
        Manage_Lab_Test manageLabTest = new Manage_Lab_Test();
        jDesktopPane1.add(manageLabTest);
        manageLabTest.show();
    }//GEN-LAST:event_jMenu20MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        jDesktopPane1.removeAll();
        Add_drugs drugManage = new Add_drugs();
        jDesktopPane1.add(drugManage);
        drugManage.show();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu17MouseClicked
        jDesktopPane1.removeAll();
        Drug_order drugOrder = new Drug_order();
        jDesktopPane1.add(drugOrder);
        drugOrder.show();
    }//GEN-LAST:event_jMenu17MouseClicked

    private void jMenu18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu18MouseClicked
        jDesktopPane1.removeAll();
        searchDrug searchDrug = new searchDrug();
        jDesktopPane1.add(searchDrug);
        searchDrug.show();
    }//GEN-LAST:event_jMenu18MouseClicked

    private void jMenu19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu19MouseClicked
        jDesktopPane1.removeAll();
        Payment_Order paymentOrder = new Payment_Order();
        jDesktopPane1.add(paymentOrder);
        paymentOrder.show();
    }//GEN-LAST:event_jMenu19MouseClicked

    private void jMenu21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu21MouseClicked
        jDesktopPane1.removeAll();
        searchLabTest searchLabTest = new searchLabTest();
        jDesktopPane1.add(searchLabTest);
        searchLabTest.show();
    }//GEN-LAST:event_jMenu21MouseClicked

    private void jMenu22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu22MouseClicked
        jDesktopPane1.removeAll();
        Order_Chemical orderChemical = new Order_Chemical();
        jDesktopPane1.add(orderChemical);
        orderChemical.show();
    }//GEN-LAST:event_jMenu22MouseClicked

    private void jMenu23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu23MouseClicked
        jDesktopPane1.removeAll();
        Manage_Patient_Lab_test managePatientLabTest = new Manage_Patient_Lab_test();
        jDesktopPane1.add(managePatientLabTest);
        managePatientLabTest.show();
    }//GEN-LAST:event_jMenu23MouseClicked

    private void jMenu24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu24MouseClicked
        jDesktopPane1.removeAll();
        Search_Patient_Lab_Test searhPatientLabTest = new Search_Patient_Lab_Test();
        jDesktopPane1.add(searhPatientLabTest);
        searhPatientLabTest.show();
    }//GEN-LAST:event_jMenu24MouseClicked

    private void jMenu25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu25MouseClicked
        jDesktopPane1.removeAll();
        manage_chemical manageChemical = new manage_chemical();
        jDesktopPane1.add(manageChemical);
        manageChemical.show();
    }//GEN-LAST:event_jMenu25MouseClicked

    private void jmApointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmApointmentMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jmApointmentMouseClicked

    private void jMenu27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu27MouseClicked
        AMain aMain = new AMain ();
        aMain.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_jMenu27MouseClicked

    private void jMenu30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu30MouseClicked
       CMain cmain = new CMain();
       cmain.setVisible(true);
    }//GEN-LAST:event_jMenu30MouseClicked

    private void jMenu31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu31MouseClicked
       PMain pmain = new PMain();
       pmain.setVisible(true);
    }//GEN-LAST:event_jMenu31MouseClicked

    private void jMenu32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu32MouseClicked
       SMain smain = new SMain();
       smain.setVisible(true);
    }//GEN-LAST:event_jMenu32MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu27;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu30;
    private javax.swing.JMenu jMenu31;
    private javax.swing.JMenu jMenu32;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JMenu jmAddUsers;
    private javax.swing.JMenu jmApointment;
    private javax.swing.JMenu jmEmpDtl;
    private javax.swing.JMenu jmLabTest;
    private javax.swing.JMenu jmNewUser;
    private javax.swing.JMenu jmPatiemtManage;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
