/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Patient_Management;

import Codes.DBconnection;
import Codes.History_Data;
import Codes.IncrementId;
import Codes.Patient_Data;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Layangi
 */
public class Check_History extends javax.swing.JInternalFrame {

    Connection c = null;
    PreparedStatement p = null;
    ResultSet rs = null;
    String pId = null;
    String pHID = null;
    String pHeight = null;
    String pWeight = null;
    String pState = null;
    String pPain = null;
    String pIllness = null;  
    String pAllergy = null;
    String pNote = null;
    String pBlood = null;
    
    Pattern letterPattern = Pattern.compile("^[a-zA-Z]+$");
    Pattern amounts = Pattern.compile("\\d{2,20}");
    Border border = (BorderFactory.createLineBorder(Color.red));
    Border border1 = (BorderFactory.createLineBorder(Color.blue));
   
    public Check_History()  {
        initComponents();
        c = DBconnection.getConnection();
        
        IncrementId pt = new IncrementId();
        String phID = pt.setId("phid","patient_history", "HIS");
        lblHisID.setText(phID);

    }

    public void p_tableLoad() {

         try {
            String sql1 = "SELECT p.pid as 'Registration ID',p.fName as 'First Name',p.lName as 'Last Name',p.age as 'Age',p.address as 'Address',p.nic as 'Nic',p.catecory as 'Catecory',p.regDate as 'Registered Date' FROM patients p";
            p = c.prepareStatement(sql1);
            rs = p.executeQuery();
            tblPatient.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }
    
    public void h_tableLoad1() {
        

         try {
            String sql1 = "SELECT p.phid as 'Patient History ID',p.ppid as 'Patient ID',p.height as 'Height (cm)',p.weight as 'Weight (kg)',p.state as 'Mental State',p.pain as 'Back Pain',p.blood as 'Blood Group',p.illness as 'Any Illness ?',p.allergy as 'Any Allergies ?', p.note as 'Note' FROM patient_history p";
            p = c.prepareStatement(sql1);
            rs = p.executeQuery();
            tblHistory.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }
    
     public void h_clearFields() {
        
        lblPatID.setText("");
        lblHisID.setText("");
        txtHeight.setText("");
        txtWeight.setText("");
        jComState.setSelectedItem("--");
        jComBlood.setSelectedItem("--");
        txtIllness.setText("");
        txtAllergies.setText("");
        jRadioY.setSelected(false);
        jRadioN.setSelected(false);
        jComState.setSelectedItem("");
        jComBlood.setSelectedItem("");
        jNote.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        txtfnme = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatient = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtIllness = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtAllergies = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jNote = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComState = new javax.swing.JComboBox();
        jRadioY = new javax.swing.JRadioButton();
        jRadioN = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jComBlood = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblHisID = new javax.swing.JLabel();
        lblPatID = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        txtPHID = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblFName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblLName = new javax.swing.JLabel();
        lblAddr = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblNo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jRadioM = new javax.swing.JRadioButton();
        jRadioF = new javax.swing.JRadioButton();

        setTitle("Check History");
        setPreferredSize(new java.awt.Dimension(1366, 550));

        txtfnme.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfnmeKeyReleased(evt);
            }
        });

        tblPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Registration ID", "First Name", "Last Name", "Age", "Address", "Contact No", "Gender", "Catecory", "Registered Date"
            }
        ));
        tblPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPatientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPatient);

        jLabel3.setText("First Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Physical Appearance");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Past History");

        jLabel14.setText("Weight ( kg )");

        jLabel15.setText("Height ( cm )");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Condition");

        jLabel17.setText("Blood Group");

        jLabel18.setText("Back Pain");

        jLabel19.setText("Had any illness to see Doctor ?");

        txtIllness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIllnessActionPerformed(evt);
            }
        });

        jLabel20.setText("Doctor's Note");

        jLabel21.setText("Any Allergies to drugs ?");

        jNote.setColumns(20);
        jNote.setRows(5);
        jScrollPane2.setViewportView(jNote);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComState.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "Normal", "Good", "Worse" }));
        jComState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComStateActionPerformed(evt);
            }
        });

        ButtonGroup2.add(jRadioY);
        jRadioY.setText("Yes");

        ButtonGroup2.add(jRadioN);
        jRadioN.setText("No");

        tblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient History ID", "Patient ID", "Height (cm)", "Weight (kg)", "Mental State", "Back Pain", "Blood Group", "Any Illness", "Any Allergies", "Doctors Note"
            }
        ));
        tblHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHistoryMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblHistory);

        jLabel22.setText("Mental State");

        jComBlood.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "A +", "A -", "B+", "B-", "AB+", "AB-", "O-", "O+" }));
        jComBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComBloodActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Patient History");

        jLabel23.setText("Patient ID   :- ");

        jLabel24.setText("Patient History ID   :-");

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel25.setText("Patient History ID");

        txtPHID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPHIDKeyReleased(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("General/On Examination");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel13.setText("First Name");

        jLabel6.setText("Last Name");

        jLabel7.setText("Address");

        jLabel8.setText("Age");

        jLabel9.setText("Contact No");

        jLabel10.setText("Gender");

        ButtonGroup2.add(jRadioM);
        jRadioM.setText("Male");
        jRadioM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioMActionPerformed(evt);
            }
        });

        ButtonGroup2.add(jRadioF);
        jRadioF.setText("Female");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(lblFName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioM)
                                .addGap(14, 14, 14)
                                .addComponent(jRadioF))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addComponent(lblAddr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioF)
                    .addComponent(jRadioM)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPatID, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(lblHisID, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82)
                .addComponent(txtPHID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(347, 347, 347))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(txtfnme, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(446, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(126, 126, 126)
                            .addComponent(jComBlood, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComState, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioY)
                                .addGap(38, 38, 38)
                                .addComponent(jRadioN))
                            .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(50, 50, 50)
                        .addComponent(jButton2)
                        .addGap(53, 53, 53)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtAllergies, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIllness, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfnme, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPHID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(53, 53, 53)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jComState, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(23, 23, 23)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jRadioY)
                                                    .addComponent(jRadioN)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lblHisID, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblPatID, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComBlood, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIllness, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtAllergies, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton3)
                                            .addComponent(jButton2)
                                            .addComponent(jButton1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(153, 153, 153)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            pId = lblPatID.getText();
            pHID = lblHisID.getText();
            pHeight = txtHeight.getText();
            pWeight = txtWeight.getText();
            pState = jComState.getSelectedItem().toString();
            if (jRadioY.isSelected()) {
              pPain = "Yes";
            } else if (jRadioN.isSelected()) {
              pPain = "No";
             }
            pIllness = txtIllness.getText();
            pAllergy = txtAllergies.getText();
            pNote = jNote.getText();
            pBlood = jComBlood.getSelectedItem().toString();
            
         if(txtHeight.equals(""))
         {  txtHeight.setEditable(true);
            txtHeight.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Height", "ERROR", JOptionPane.ERROR_MESSAGE);
         }    
         if(txtWeight.equals(""))
         {  txtWeight.setEditable(true);
            txtWeight.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Weight", "ERROR", JOptionPane.ERROR_MESSAGE);
         }    
         if(txtIllness.equals(""))
         {  txtIllness.setEditable(true);
            txtIllness.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Illness", "ERROR", JOptionPane.ERROR_MESSAGE);
         }  
         if(jNote.equals(""))
         {  jNote.setEditable(true);
            jNote.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Note", "ERROR", JOptionPane.ERROR_MESSAGE);
         }  
         if(txtAllergies.equals(""))
         {  txtAllergies.setEditable(true);
            txtAllergies.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Allergies", "ERROR", JOptionPane.ERROR_MESSAGE);
         }    
         if(jComBlood.equals("--"))
         {  jComBlood.setEditable(true);
            jComBlood.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Status", "ERROR", JOptionPane.ERROR_MESSAGE);
         }
     /*     if(!(jRadioY.isSelected()) || !(jRadioN.isSelected()))
         {  
            JOptionPane.showMessageDialog(null, "Enter Back pain", "ERROR", JOptionPane.ERROR_MESSAGE);
         }
             */
         if(jComState.equals("--"))
         {  jComState.setEditable(true);
            jComState.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Status", "ERROR", JOptionPane.ERROR_MESSAGE);
         }
         else if(!(amounts.matcher(txtHeight.getText()).matches()) ){
             JOptionPane.showMessageDialog(null, "Height must be a number", "ERROR", JOptionPane.ERROR_MESSAGE);  
             txtHeight.setEditable(true);
             txtHeight.setBorder(border);
          }
         else if(!(amounts.matcher(txtWeight.getText()).matches()) ){
             JOptionPane.showMessageDialog(null, "Weight must be a number", "ERROR", JOptionPane.ERROR_MESSAGE);  
             txtWeight.setEditable(true);
             txtWeight.setBorder(border);
          } 
        else {
             
         txtHeight.setEditable(true);
         txtHeight.setBorder(border1);
            
         txtWeight.setEditable(true);
         txtWeight.setBorder(border1);
                               
         jComState.setEditable(true);
         jComState.setBorder(border1);
         
         jComBlood.setEditable(true);
         jComBlood.setBorder(border1);
            
         txtIllness.setEditable(true);
         txtIllness.setBorder(border1);
            
         txtAllergies.setEditable(true);
         txtAllergies.setBorder(border1);
          
         jNote.setEditable(true);
         jNote.setBorder(border1);
                  
        int x = JOptionPane.showConfirmDialog(rootPane, "Do you want to add history details of this patient?");
       
        if(x==0){
                History_Data pSave = new History_Data();
                pSave.save(pId, pHID, pHeight, pWeight, pState, pPain, pIllness, pAllergy, pNote, pBlood);
                
                h_tableLoad1();
                h_clearFields();
                         
            }
         }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            pId = lblPatID.getText();
            pHID = lblHisID.getText();
            pHeight = txtHeight.getText();
            pWeight = txtWeight.getText();
            pState = jComState.getSelectedItem().toString();
            if (jRadioY.isSelected()) {
              pPain = "Yes";
            } else if (jRadioN.isSelected()) {
              pPain = "No";
             }
            pIllness = txtIllness.getText();
            pAllergy = txtAllergies.getText();
            pNote = jNote.getText();
            pBlood = jComBlood.getSelectedItem().toString();
            
        if(txtHeight.equals(""))
         {  txtHeight.setEditable(true);
            txtHeight.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Height", "ERROR", JOptionPane.ERROR_MESSAGE);
         }    
         if(txtWeight.equals(""))
         {  txtWeight.setEditable(true);
            txtWeight.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Weight", "ERROR", JOptionPane.ERROR_MESSAGE);
         }    
         if(txtIllness.equals(""))
         {  txtIllness.setEditable(true);
            txtIllness.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Illness", "ERROR", JOptionPane.ERROR_MESSAGE);
         }  
         if(jNote.equals(""))
         {  jNote.setEditable(true);
            jNote.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Note", "ERROR", JOptionPane.ERROR_MESSAGE);
         }  
         if(txtAllergies.equals(""))
         {  txtAllergies.setEditable(true);
            txtAllergies.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Allergies", "ERROR", JOptionPane.ERROR_MESSAGE);
         }    
         if(jComBlood.equals("--"))
         {  jComBlood.setEditable(true);
            jComBlood.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Status", "ERROR", JOptionPane.ERROR_MESSAGE);
         }
     /*     if(!(jRadioY.isSelected()) || !(jRadioN.isSelected()))
         {  
            JOptionPane.showMessageDialog(null, "Enter Back pain", "ERROR", JOptionPane.ERROR_MESSAGE);
         }
             */
         if(jComState.equals("--"))
         {  jComState.setEditable(true);
            jComState.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Status", "ERROR", JOptionPane.ERROR_MESSAGE);
         }
         else if(!(amounts.matcher(txtHeight.getText()).matches()) ){
             JOptionPane.showMessageDialog(null, "Height must be a number", "ERROR", JOptionPane.ERROR_MESSAGE);  
             txtHeight.setEditable(true);
             txtHeight.setBorder(border);
          }
         else if(!(amounts.matcher(txtWeight.getText()).matches()) ){
             JOptionPane.showMessageDialog(null, "Weight must be a number", "ERROR", JOptionPane.ERROR_MESSAGE);  
             txtWeight.setEditable(true);
             txtWeight.setBorder(border);
          } 
        else {
             
         txtHeight.setEditable(true);
         txtHeight.setBorder(border1);
            
         txtWeight.setEditable(true);
         txtWeight.setBorder(border1);
                               
         jComState.setEditable(true);
         jComState.setBorder(border1);
         
         jComBlood.setEditable(true);
         jComBlood.setBorder(border1);
            
         txtIllness.setEditable(true);
         txtIllness.setBorder(border1);
            
         txtAllergies.setEditable(true);
         txtAllergies.setBorder(border1);
          
         jNote.setEditable(true);
         jNote.setBorder(border1);
         
         int x = JOptionPane.showConfirmDialog(null, "Do you need to update the patient history?");
                  
            if(x==0){
                History_Data hUpdate = new History_Data();
                hUpdate.update(pId, pHID, pHeight, pWeight, pState, pPain, pIllness, pAllergy, pNote, pBlood);
                
                h_tableLoad1();
                h_clearFields();
            }
         }  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComStateActionPerformed

    private void txtfnmeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfnmeKeyReleased
       
        String register = txtfnme.getText();
        try {
           String ses = "SELECT pid as 'Registration ID',fName as 'First Name',lName as 'Last Name',age as 'Age',address as 'Address',contact as 'Contact No',gender as 'Gender',catecory as 'Catecory',regDate as 'Registered Date' FROM patient WHERE fname like '%" + register + "'or pid like '%" + register + "%' ";
           p = c.prepareStatement(ses);
           rs = p.executeQuery();
           tblPatient.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_txtfnmeKeyReleased

    private void tblPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPatientMouseClicked
        
        int r = tblPatient.getSelectedRow();
 
        lblPatID.setText(tblPatient.getValueAt(r, 0).toString());
        lblFName.setText(tblPatient.getValueAt(r, 1).toString());
        lblLName.setText(tblPatient.getValueAt(r, 2).toString());
        lblAge.setText(tblPatient.getValueAt(r, 3).toString());
        lblAddr.setText(tblPatient.getValueAt(r, 4).toString());
        lblNo.setText(tblPatient.getValueAt(r, 5).toString());
        String GN = tblPatient.getValueAt(r, 6).toString();
            if (GN =="Female"){
                jRadioM.setSelected(false);
                jRadioF.setSelected(true);
            }
            else{
                jRadioF.setSelected(false);
                jRadioM.setSelected(true);
            }     
        
    }//GEN-LAST:event_tblPatientMouseClicked

    private void tblHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHistoryMouseClicked
        int r = tblHistory.getSelectedRow();

        lblHisID.setText(tblHistory.getValueAt(r, 0).toString());
        lblPatID.setText(tblHistory.getValueAt(r, 1).toString());
        txtHeight.setText(tblHistory.getValueAt(r, 2).toString());
        txtWeight.setText(tblHistory.getValueAt(r, 3).toString());
        jComState.setSelectedItem(tblHistory.getValueAt(r, 4).toString());
         String GN = tblHistory.getValueAt(r, 5).toString();
            if (GN =="Yes"){
                jRadioN.setSelected(false);
                jRadioY.setSelected(true);
            }
            else{
                jRadioY.setSelected(false);
                jRadioN.setSelected(true);
            }     
        jComBlood.setSelectedItem(tblHistory.getValueAt(r, 6).toString());
        txtIllness.setText(tblHistory.getValueAt(r, 7).toString());
        txtAllergies.setText(tblHistory.getValueAt(r, 8).toString());
        jNote.setText(tblHistory.getValueAt(r, 9).toString());
    }//GEN-LAST:event_tblHistoryMouseClicked

    private void jComBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComBloodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComBloodActionPerformed

    private void jRadioMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioMActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         
        pHID = lblHisID.getText();
        int x = JOptionPane.showConfirmDialog(this, "Do You Want to delete the record");

        if (x == 0) {

            History_Data hDelete = new History_Data();
            hDelete.delete(pHID);
        }       
         h_tableLoad1();
         h_clearFields(); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtPHIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPHIDKeyReleased
         String his = txtPHID.getText();
        try {
            String ses = "SELECT phid as 'Patient History ID',ppid as 'Patient ID',height as 'Height (cm)',weight as 'Weight (kg)',state as 'Mental State',pain as 'Back Pain',blood as 'Blood Group',illness as 'Any Illness ?',allergy as 'Any Allergies ?',note as 'Doctors Note' FROM patient_history WHERE phid like '%" + his + "'or ppid like '%" + his + "%' ";  
         //  String ses = "SELECT supId as 'Supplier ID',supName as 'Supplier Name',brand as 'Company Name',email as 'Email' FROM supplier WHERE supName like '%" + sname + "%'or supId like '%" + sname + "%' "; 
           p = c.prepareStatement(ses);
           rs = p.executeQuery();
           tblHistory.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_txtPHIDKeyReleased

    private void txtIllnessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIllnessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIllnessActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ButtonGroup2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComBlood;
    private javax.swing.JComboBox jComState;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea jNote;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioF;
    private javax.swing.JRadioButton jRadioM;
    private javax.swing.JRadioButton jRadioN;
    private javax.swing.JRadioButton jRadioY;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAddr;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblHisID;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblPatID;
    private javax.swing.JTable tblHistory;
    private javax.swing.JTable tblPatient;
    private javax.swing.JTextField txtAllergies;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtIllness;
    private javax.swing.JTextField txtPHID;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JTextField txtfnme;
    // End of variables declaration//GEN-END:variables
}
