/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Patient_Management;

import Codes.DBconnection;
import Codes.Diagnosis_Data;
import Codes.IncrementId;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Layangi
 */
public class Diagnosis extends javax.swing.JInternalFrame {

    Connection c = null;
    PreparedStatement p = null;
    ResultSet rs = null;
    String diseaseId = null;
    String patientId = null;
    String pSigns = null;
    String pGeneral = null;
    String pSystemic = null;
    String pDiagnosis = null;
    
    Pattern amounts = Pattern.compile("\\d{2,20}");
    Border border = (BorderFactory.createLineBorder(Color.red));
    Border border1 = (BorderFactory.createLineBorder(Color.blue));
   
    
    public Diagnosis() {
        initComponents();
        c = DBconnection.getConnection();
        
        IncrementId ID = new IncrementId();
        String did = ID.setId("dId", "diagnosis", "DIAG");
        lblDiag.setText(did); 
          
    }

    public void p_tableLoad() {

         try {
            String sql1 = "SELECT pid as 'Registration ID',fName as 'First Name',age as 'Age',catecory as 'Catecory' FROM patient";
            p = c.prepareStatement(sql1);
            rs = p.executeQuery();
            tblPData.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }
     
     public void d_tableLoad() {

         try {
            String sql1 = "SELECT s.dId as 'Diagnosis ID',s.disease as 'Diagnosis',s.ptpid as 'Patient ID',p.fname as 'Patient Name',p.age as 'Age',s.signs as 'Signs And Symptoms',s.general as 'General Findings',s.systemic as 'Systemic Findings' FROM diagnosis s , patient p WHERE p.pid=s.ptpid";
            p = c.prepareStatement(sql1);
            rs = p.executeQuery();
            tbldiag.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }
    
     public void d_clearFields() {        
            lblDiag.setText("");
            lblId.setText("");
            txtname.setText("");
            txtAge.setText("");
            txtSigns.setText("");
            txtGen.setText("");
            txtSys.setText("");
            txtDiag.setText("");   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPData = new javax.swing.JTable();
        lblId = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSys = new javax.swing.JTextField();
        txtGen = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbldiag = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        lblDiag = new javax.swing.JLabel();
        txtname = new javax.swing.JLabel();
        txtAge = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtSigns = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        txtDiag = new javax.swing.JTextField();

        setTitle("Diagnosis Details");

        jLabel1.setText("Patient Name");

        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Diagnosis Details");

        jLabel3.setText("Signs & Symptoms of the Disease");

        jLabel4.setText("Patient ID");

        jLabel5.setText("Name");

        jLabel6.setText("Age");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Examination");

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tblPData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "First Name", "Last Name", "Age"
            }
        ));
        tblPData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPDataMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblPData);

        jLabel10.setText("General Findings");

        jLabel11.setText("Systemic Findings");

        tbldiag.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Diagnosis ID", "Diagnosis", "Patient ID", "Patient Name", "Age", "Signs And Symptoms", "nullGeneral Findings", "Systemic Findings"
            }
        ));
        tbldiag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldiagMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbldiag);

        jLabel9.setText("Disease ID");

        txtSigns.setColumns(20);
        txtSigns.setRows(5);
        jScrollPane6.setViewportView(txtSigns);

        jLabel16.setText("Diagnosis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(74, 74, 74))
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDiag, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jButton2)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jButton3))
                                                .addComponent(txtSys, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtGen, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtDiag, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(52, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDiag, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         
        if(txtSigns.equals(""))
         {  txtSigns.setEditable(true);
            txtSigns.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Signs & Symptoms", "ERROR", JOptionPane.ERROR_MESSAGE);
         }    
         if(txtGen.equals(""))
         {  txtGen.setEditable(true);
            txtGen.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Genearal Findings", "ERROR", JOptionPane.ERROR_MESSAGE);
         }    
         if(txtSys.equals(""))
         {  txtSys.setEditable(true);
            txtSys.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Systemic Findings", "ERROR", JOptionPane.ERROR_MESSAGE);
         }   
         if(txtDiag.equals(""))
         {  txtDiag.setEditable(true);
            txtDiag.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter the disease", "ERROR", JOptionPane.ERROR_MESSAGE);
         }    
        
         else{
             
         txtSigns.setEditable(true);
         txtSigns.setBorder(border1);
            
         txtGen.setEditable(true);
         txtGen.setBorder(border1);
            
         txtSys.setEditable(true);
         txtSys.setBorder(border1);
            
         txtDiag.setEditable(true);
         txtDiag.setBorder(border1);
         
        int x = JOptionPane.showConfirmDialog(rootPane, "Do you want to Add the diagnosis details of the patient ?");

        if (x == 0) {
            
            diseaseId = lblDiag.getText();
            patientId = lblId.getText();
            pSigns = txtSigns.getText();
            pGeneral = txtGen.getText();
            pSystemic = txtSys.getText();
            pDiagnosis = txtDiag.getText();
            
            if(pSigns.isEmpty() || pGeneral.isEmpty() || pSystemic.isEmpty()) {
                JOptionPane.showMessageDialog(this, "You Should Fill All Fields");
            }
            else {
                Diagnosis_Data dSave = new Diagnosis_Data();
                dSave.save(diseaseId, patientId, pSigns, pGeneral, pSystemic, pDiagnosis);
                
                d_tableLoad();
                d_clearFields();            
         }  
        } 
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        if(txtSigns.equals(""))
         {  txtSigns.setEditable(true);
            txtSigns.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Signs & Symptoms", "ERROR", JOptionPane.ERROR_MESSAGE);
         }    
         if(txtGen.equals(""))
         {  txtGen.setEditable(true);
            txtGen.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Genearal Findings", "ERROR", JOptionPane.ERROR_MESSAGE);
         }    
         if(txtSys.equals(""))
         {  txtSys.setEditable(true);
            txtSys.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Systemic Findings", "ERROR", JOptionPane.ERROR_MESSAGE);
         }   
         if(txtDiag.equals(""))
         {  txtDiag.setEditable(true);
            txtDiag.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter the disease", "ERROR", JOptionPane.ERROR_MESSAGE);
         }    
        
         else{
             
         txtSigns.setEditable(true);
         txtSigns.setBorder(border1);
            
         txtGen.setEditable(true);
         txtGen.setBorder(border1);
            
         txtSys.setEditable(true);
         txtSys.setBorder(border1);
            
         txtDiag.setEditable(true);
         txtDiag.setBorder(border1);
         
        int ans = JOptionPane.showConfirmDialog(null, "Do you need to update the diagnosis details of the patient?");

        if (ans == 0) {
            
            diseaseId = lblDiag.getText();
            patientId = lblId.getText();
            pSigns = txtSigns.getText();
            pGeneral = txtGen.getText();
            pSystemic = txtSys.getText();
            pDiagnosis = txtDiag.getText();

                Diagnosis_Data dUpdate = new Diagnosis_Data();
                dUpdate.update(diseaseId,patientId, pSigns, pGeneral, pSystemic, pDiagnosis);
                
                d_tableLoad();
                d_clearFields();
        }        
      }  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyReleased
        
        String ID = txtID.getText();
        try {
           String ses = "SELECT pid as 'Registration ID',fName as 'First Name',age as 'Age',catecory as 'Catecory' FROM patient WHERE fname like '%" + ID + "'or pid like '%" + ID + "%' ";

           p = c.prepareStatement(ses);
           rs = p.executeQuery();
           tblPData.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_txtIDKeyReleased

    private void tbldiagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldiagMouseClicked
        int r = tbldiag.getSelectedRow();

        lblDiag.setText(tbldiag.getValueAt(r, 0).toString());
        txtDiag.setText(tbldiag.getValueAt(r, 1).toString());
        lblId.setText(tbldiag.getValueAt(r, 2).toString());
        txtname.setText(tbldiag.getValueAt(r, 3).toString());
        txtAge.setText(tbldiag.getValueAt(r, 4).toString());
        txtSigns.setText(tbldiag.getValueAt(r, 5).toString());
        txtGen.setText(tbldiag.getValueAt(r, 6).toString());
        txtSys.setText(tbldiag.getValueAt(r, 7).toString());
 
    }//GEN-LAST:event_tbldiagMouseClicked

    private void tblPDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPDataMouseClicked
        int r = tblPData.getSelectedRow();

        lblId.setText(tblPData.getValueAt(r, 0).toString());
        txtname.setText(tblPData.getValueAt(r, 1).toString());
        txtAge.setText(tblPData.getValueAt(r, 2).toString());
    }//GEN-LAST:event_tblPDataMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblDiag;
    private javax.swing.JLabel lblId;
    private javax.swing.JTable tblPData;
    private javax.swing.JTable tbldiag;
    private javax.swing.JLabel txtAge;
    private javax.swing.JTextField txtDiag;
    private javax.swing.JTextField txtGen;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextArea txtSigns;
    private javax.swing.JTextField txtSys;
    private javax.swing.JLabel txtname;
    // End of variables declaration//GEN-END:variables
}
