/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Patient_Management;

import Codes.DBconnection;
import Codes.IncrementId;
import Codes.Patient_Data;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Layangi
 */
public class Register_Patients extends javax.swing.JInternalFrame {

    Connection c = null;
    PreparedStatement p = null;
    ResultSet rs = null;
    
    String pPid = null;
    String pFName = null;
    String pLName = null;
    String pAge = null;
    String pGender = null;
    String pAddress = null;
    String pContact = null;
    String pNic = null;
    String pCat = null;
    String pDate = null;
    Pattern letterPattern = Pattern.compile("^[a-zA-Z]+$");
    Pattern amounts = Pattern.compile("\\d{2,20}");
    Border border = (BorderFactory.createLineBorder(Color.red));
    Border border1 = (BorderFactory.createLineBorder(Color.blue));

    public Register_Patients() {
        initComponents();
        c = DBconnection.getConnection();

        java.util.Date today = new java.util.Date(); //get System date
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        pDate = df.format(today);
        txtDte.setText(pDate);
        
        IncrementId pt = new IncrementId();
        String ptID = pt.setId("pid","patient", "REG");
        txtReg.setText(ptID);
        
        tableLoad();
    }
    public void tableLoad() {

        try {
            String sql1 = "SELECT pid as 'Registration ID',fName as 'First Name',lName as 'Last Name',age as 'Age',gender as 'Gender',address as 'Address',contact as 'Contact No',nic as 'Nic',catecory as 'Catecory',regDate as 'Registered Date' FROM patient";
            p = c.prepareStatement(sql1);
            rs = p.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }

    public void clearFields() {

        txtReg.setText("");
        txtFname.setText("");
        txtLname.setText("");
        txtAge.setText("");
        RadioM.setSelected(false);
        RadioF.setSelected(false);
        txtAddress.setText("");
        txtContact.setText("");
        txtNic.setText("");
        jComCat.setSelectedItem("--");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtNic = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        txtRegNo2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        RadioM = new javax.swing.JRadioButton();
        RadioF = new javax.swing.JRadioButton();
        jComCat = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDte = new javax.swing.JLabel();
        txtReg = new javax.swing.JLabel();
        Reset = new javax.swing.JButton();

        setTitle("Register Patients");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Patient Details");

        jLabel2.setText("First Name");

        jLabel4.setText("Last Name");

        jLabel5.setText("Age");

        jLabel6.setText("Gender");

        jLabel7.setText("Address");

        jLabel8.setText("Contact No");

        txtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnameActionPerformed(evt);
            }
        });

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("View ");

        jLabel10.setText("Registration No");

        jLabel11.setText("NIC");

        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });

        jLabel12.setText("Name");

        txtRegNo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegNo2ActionPerformed(evt);
            }
        });
        txtRegNo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRegNo2KeyReleased(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registration ID", "First Name", "Last Name", "Age", "Address", "Nic", "Catecory", "Registered Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete Record");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        RadioM.setText("Male");

        RadioF.setText("Female");
        RadioF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioFActionPerformed(evt);
            }
        });

        jComCat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "Critical", "Non- Critical" }));
        jComCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComCatActionPerformed(evt);
            }
        });

        jLabel14.setText("Registration No");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registration ID", "First Name", "Last Name", "Age", "Address", "Nic", "Catecory", "Registered Date"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel15.setText("Catecory");

        jLabel16.setText("Date");

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RadioM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RadioF))
                            .addComponent(txtLname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAge, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContact, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNic, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComCat, javax.swing.GroupLayout.Alignment.LEADING, 0, 151, Short.MAX_VALUE)
                            .addComponent(txtFname, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(txtReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDte, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(85, 85, 85)
                                    .addComponent(txtRegNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(61, 61, 61)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(50, 50, 50)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel9)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(35, 35, 35)
                        .addComponent(Reset)))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(507, 507, 507))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtReg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtRegNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioM)
                            .addComponent(RadioF))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNic, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDte, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(Reset))
                        .addContainerGap(53, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioFActionPerformed

    private void jComCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComCatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        pPid = txtReg.getText();
        pFName = txtFname.getText();
        pLName = txtLname.getText();
        pAge = txtAge.getText();
        if (RadioM.isSelected()) {
          pGender = "Male";
        } else if (RadioF.isSelected()) {
            pGender = "Female";
        }
        pAddress = txtAddress.getText();
        pContact = txtContact.getText();
        pNic = txtNic.getText();
        pCat = jComCat.getSelectedItem().toString();
        pDate = txtDte.getText();
        
        //Contact No validation
        //String number = "012-1234567"; 
        Pattern pattern = Pattern.compile("\\d{3}-\\d{7}");
        Matcher matcher = pattern.matcher(pContact); 
        
         if(txtFname.equals(""))
         {  txtFname.setEditable(true);
            txtFname.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter First Name", "ERROR", JOptionPane.ERROR_MESSAGE);
         }    
         if(txtLname.equals(""))
         {  txtLname.setEditable(true);
            txtLname.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Last Name", "ERROR", JOptionPane.ERROR_MESSAGE);
         }    
         if(txtAge.equals(""))
         {  txtAge.setEditable(true);
            txtAge.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Age", "ERROR", JOptionPane.ERROR_MESSAGE);
         }   
         if(txtAddress.equals(""))
         {  txtAddress.setEditable(true);
            txtAddress.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Address", "ERROR", JOptionPane.ERROR_MESSAGE);
         }    
         if(txtContact.equals(""))
         {  txtContact.setEditable(true);
            txtContact.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Contact No", "ERROR", JOptionPane.ERROR_MESSAGE);
         }    
         if(txtNic.equals(""))
         {  txtNic.setEditable(true);
            txtNic.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Age", "ERROR", JOptionPane.ERROR_MESSAGE);
         }    
         if(jComCat.equals(""))
         {  jComCat.setEditable(true);
            jComCat.setBorder(border);
            JOptionPane.showMessageDialog(null, "Enter Status", "ERROR", JOptionPane.ERROR_MESSAGE);
         }
         else if(!(amounts.matcher(txtAge.getText()).matches()) ){
             JOptionPane.showMessageDialog(null, "Age must be a number", "ERROR", JOptionPane.ERROR_MESSAGE);  
             txtAge.setEditable(true);
             txtAge.setBorder(border);
          }
         else if(!(txtNic.getText().trim().matches("^[0-9]{9}[vVxX]$"))){
             JOptionPane.showMessageDialog(null,"Invalid NIC","ERROR", JOptionPane.ERROR_MESSAGE);
             txtNic.setEditable(true);
             txtNic.setBorder(border);
        }   
         else if(!(matcher.matches())) {
              JOptionPane.showMessageDialog(null,"Invalid Phone No","ERROR", JOptionPane.ERROR_MESSAGE);
              txtContact.setEditable(true);
              txtContact.setBorder(border);
          }
          
      /*   else if(!(txtwid.getText().startsWith("WRN")))
         {
         txtwid.setEditable(true);
         txtwid.setBorder(border);
         JOptionPane.showMessageDialog(null, "Enter a Valid  Warranty ID", "ERROR", JOptionPane.ERROR_MESSAGE);
         }  
        
         */
         else{
         txtFname.setEditable(true);
         txtFname.setBorder(border1);
            
         txtLname.setEditable(true);
         txtLname.setBorder(border1);
            
         txtAge.setEditable(true);
         txtAge.setBorder(border1);
            
         txtAddress.setEditable(true);
         txtAddress.setBorder(border1);
            
         txtContact.setEditable(true);
         txtContact.setBorder(border1);
            
         txtNic.setEditable(true);
         txtNic.setBorder(border1);
            
         jComCat.setEditable(true);
         jComCat.setBorder(border1);

        
        int x= JOptionPane.showConfirmDialog(null, "Do You Want To Register This Patient ?");
      
      if(x==0)
      {
             Patient_Data pSave = new Patient_Data();
             pSave.save(pPid, pFName, pLName, pAge, pGender, pAddress, pContact, pNic, pCat, pDate);
            
             tableLoad();
             clearFields();               
         }  
      }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtRegNo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegNo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegNo2ActionPerformed

    private void txtRegNo2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegNo2KeyReleased

        String register = txtRegNo2.getText();
        try {
            String ses = "SELECT pid as 'Registration ID',fName as 'First Name',lName as 'Last Name',age as 'Age',address as 'Address',nic as 'Nic',catecory as 'Catecory',regDate as 'Registered Date' FROM patient WHERE fname like '%" + register + "'or pid like '%" + register + "%' ";
            p = c.prepareStatement(ses);
            rs = p.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_txtRegNo2KeyReleased

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameActionPerformed

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

       String pPid = txtReg.getText();
        int x = JOptionPane.showConfirmDialog(this, "Do You Want to delete the registered patient record");

        if (x == 0) {

            Patient_Data pDelete = new Patient_Data();
            pDelete.delete(pPid);        
        }       
         tableLoad();
         clearFields();      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int r = jTable2.getSelectedRow();

        txtReg.setText(jTable2.getValueAt(r, 0).toString());
        txtFname.setText(jTable2.getValueAt(r, 1).toString());
        txtLname.setText(jTable2.getValueAt(r, 2).toString());
        txtAge.setText(jTable2.getValueAt(r, 3).toString()); 
        String GN = jTable2.getValueAt(r, 4).toString();
            if (GN =="Female"){
                RadioM.setSelected(false);
                RadioF.setSelected(true);
            }
            else{
                RadioF.setSelected(false);
                RadioM.setSelected(true);
            }      
        txtAddress.setText(jTable2.getValueAt(r, 5).toString());
        txtContact.setText(jTable2.getValueAt(r, 6).toString());
        txtNic.setText(jTable2.getValueAt(r, 7).toString());
        jComCat.setSelectedItem(jTable2.getValueAt(r, 8).toString());
        txtDte.setText(jTable2.getValueAt(r, 9).toString());

    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         pPid = txtReg.getText();
         pFName = txtFname.getText();
         pLName = txtLname.getText();
         pAge = txtAge.getText();
         if (RadioM.isSelected()) {
         pGender = "Male";
         } else if (RadioF.isSelected()) {
         pGender = "Female";
         }
         pAddress = txtAddress.getText();
         pContact = txtContact.getText();
         pNic = txtNic.getText();
         pCat = jComCat.getSelectedItem().toString();
        
         Pattern pattern = Pattern.compile("\\d{3}-\\d{7}");
         Matcher matcher = pattern.matcher(pContact); 
        
         if(txtFname.equals(""))
         {  txtFname.setEditable(true);
         txtFname.setBorder(border);
         JOptionPane.showMessageDialog(null, "Enter First Name", "ERROR", JOptionPane.ERROR_MESSAGE);
         }    
         if(txtLname.equals(""))
         {  txtLname.setEditable(true);
         txtLname.setBorder(border);
         JOptionPane.showMessageDialog(null, "Enter Last Name", "ERROR", JOptionPane.ERROR_MESSAGE);
         }    
         if(txtAge.equals(""))
         {  txtAge.setEditable(true);
         txtAge.setBorder(border);
         JOptionPane.showMessageDialog(null, "Enter Age", "ERROR", JOptionPane.ERROR_MESSAGE);
         }   
         if(txtAddress.equals(""))
         {  txtAddress.setEditable(true);
         txtAddress.setBorder(border);
         JOptionPane.showMessageDialog(null, "Enter Address", "ERROR", JOptionPane.ERROR_MESSAGE);
         }    
         if(txtContact.equals(""))
         {  txtContact.setEditable(true);
         txtContact.setBorder(border);
         JOptionPane.showMessageDialog(null, "Enter Contact No", "ERROR", JOptionPane.ERROR_MESSAGE);
         }    
         if(txtNic.equals(""))
         {  txtNic.setEditable(true);
         txtNic.setBorder(border);
         JOptionPane.showMessageDialog(null, "Enter Age", "ERROR", JOptionPane.ERROR_MESSAGE);
         }    
         if(jComCat.equals(""))
         {  jComCat.setEditable(true);
         jComCat.setBorder(border);
         JOptionPane.showMessageDialog(null, "Enter Status", "ERROR", JOptionPane.ERROR_MESSAGE);
          }
         
         else if(!(txtNic.getText().trim().matches("^[0-9]{9}[vVxX]$"))){
         JOptionPane.showMessageDialog(null,"Invalid NIC","ERROR", JOptionPane.ERROR_MESSAGE);
         txtNic.setEditable(true);
         txtNic.setBorder(border);
         } 
         else if(!(matcher.matches())) {
            JOptionPane.showMessageDialog(null,"Invalid Phone No","ERROR", JOptionPane.ERROR_MESSAGE);
            txtContact.setEditable(true);
            txtContact.setBorder(border);
          }
        /*   else if(!(txtwid.getText().startsWith("WRN")))
         {
         txtwid.setEditable(true);
         txtwid.setBorder(border);
         JOptionPane.showMessageDialog(null, "Enter a Valid  Warranty ID", "ERROR", JOptionPane.ERROR_MESSAGE);
         }  
        
         */

         else{  
         txtFname.setEditable(true);
         txtFname.setBorder(border1);
            
         txtLname.setEditable(true);
         txtLname.setBorder(border1);
            
         txtAge.setEditable(true);
         txtAge.setBorder(border1);
            
         txtAddress.setEditable(true);
         txtAddress.setBorder(border1);
            
         txtContact.setEditable(true);
         txtContact.setBorder(border1);
            
         txtNic.setEditable(true);
         txtNic.setBorder(border1);
            
         jComCat.setEditable(true);
         jComCat.setBorder(border1);

         int x= JOptionPane.showConfirmDialog(null, "Do You Want To Update This Registerd Patient Details ?");
      
         if(x==0)
         {
         Patient_Data pUpdate = new Patient_Data();
         pUpdate.update(pPid, pFName, pLName, pAge, pGender, pAddress, pContact, pNic, pCat);
            
         tableLoad();
         clearFields();
         }
      }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        clearFields();
    }//GEN-LAST:event_ResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioF;
    private javax.swing.JRadioButton RadioM;
    private javax.swing.JButton Reset;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComCat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtContact;
    private javax.swing.JLabel txtDte;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtNic;
    private javax.swing.JLabel txtReg;
    private javax.swing.JTextField txtRegNo2;
    // End of variables declaration//GEN-END:variables
}
