/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy_lab;

import code.DBconnection;
import code.IncrementId;
import code.chemical_management;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Lakshika
 */
public class manage_chemical extends javax.swing.JInternalFrame {

    /**
     * Creates new form manage_chemical
     */
    Connection c = null;
    PreparedStatement p = null;
    ResultSet rs = null;

    public manage_chemical() {
        initComponents();

        c = DBconnection.getConnection();

        IncrementId mf = new IncrementId();
        String did = mf.setId("chemCode", "chemical", "CHEM");

        lblChemCode.setText(did);

        tableload();
    }

    public void tableload() {

        try {
            String ses = "SELECT supId as 'Supplier ID',supName as 'Supplier Name',brand as 'Company Name',email as 'Email' "
                    + "FROM supplier ";
            p = c.prepareStatement(ses);
            rs = p.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            System.out.println(ex);
        }

        try {

            String sql1 = "SELECT c.chemCode as 'Chemical Code',c.chemName as 'Chemical Name',c.type as 'Type',c.qty as 'Weight/Concenration',c.supId as 'Supplier ID',c.price as 'Price' "
                    + "FROM chemical c WHERE c.status = 'NT'";
            p = c.prepareStatement(sql1);
            rs = p.executeQuery();
            tblChemicalDetails.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            System.out.println(ex);
        }

    }

    public void clearfield() {

        txtChemName.setText("");
        txtConcentration.setText("");
        txtWeight.setText("");
        cmbChemType.setSelectedIndex(0);
        txtPrice.setText("0.0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblChemicalDetails = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblChemCode = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtChemName = new javax.swing.JTextField();
        cmbChemType = new javax.swing.JComboBox<>();
        txtConcentration = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtSname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblSid = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblSname = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setTitle("Manage Chemical ");
        setPreferredSize(new java.awt.Dimension(1366, 550));

        tblChemicalDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Chemical Code", "Chemical Name", "Type", "Weight / Concentration", "Supplier ID", "Price"
            }
        ));
        tblChemicalDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChemicalDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChemicalDetails);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chemical Details"));

        jLabel2.setText("Chemical Name");

        jLabel3.setText("Chemical Type");

        jLabel4.setText("Concentration");

        lblChemCode.setText("Chemical Code");

        jLabel5.setText("Weight");

        cmbChemType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type", "Solid", "Hydraulic", "Tapes" }));
        cmbChemType.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cmbChemTypeMouseMoved(evt);
            }
        });
        cmbChemType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbChemTypeMouseClicked(evt);
            }
        });

        jLabel1.setText("Chemical Code");

        jLabel9.setText("Price");

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblChemCode)
                    .addComponent(txtChemName)
                    .addComponent(cmbChemType, 0, 116, Short.MAX_VALUE)
                    .addComponent(txtConcentration)
                    .addComponent(txtWeight)
                    .addComponent(txtPrice))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblChemCode))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtChemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbChemType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtConcentration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Serach Supplier By Name Or ID"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSnameKeyReleased(evt);
            }
        });
        jPanel2.add(txtSname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 224, -1));

        jLabel6.setText("Supplier ID");

        lblSid.setText("Supplier ID");

        jLabel7.setText("Supplier Name");

        lblSname.setText("Supplier Name");

        jLabel8.setText("Company Name");

        lblBrand.setText("Company Name");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Supplier ID", "Supplier Name", "Comany Name", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(108, 108, 108)
                                .addComponent(lblSid, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(92, 92, 92)
                                .addComponent(lblSname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(85, 85, 85)
                                .addComponent(lblBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jButton2)
                                .addGap(54, 54, 54)
                                .addComponent(jButton3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblSid))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblSname))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(lblBrand))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String tchemCode = lblChemCode.getText();
        String tchemName = txtChemName.getText();
        String ttype = cmbChemType.getSelectedItem().toString();
        String tcon = txtConcentration.getText();
        String tweight = txtWeight.getText();
        String supId = lblSid.getText();
        double price = Double.parseDouble(txtPrice.getText());
        
        chemical_management a = new chemical_management();
        
        if (tchemCode.isEmpty() || tchemName.isEmpty() || ttype.isEmpty() || supId.isEmpty() || price == 0.0) {

            JOptionPane.showMessageDialog(this, "You Should Fill All Fields");
        } else if (!tcon.isEmpty()) {

            a.addChemical(tchemCode, tchemName, ttype, tcon, supId,price);

            tableload();
            clearfield();

        } else if (!tweight.isEmpty()) {
            
            a.addChemical(tchemCode, tchemName, ttype, tweight, supId,price);

            tableload();
            clearfield();
        }
        IncrementId mf = new IncrementId();
        String did = mf.setId("chemCode", "chemical", "CHEM");

        lblChemCode.setText(did);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbChemTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbChemTypeMouseClicked


    }//GEN-LAST:event_cmbChemTypeMouseClicked

    private void cmbChemTypeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbChemTypeMouseMoved
        txtConcentration.setEnabled(true);
        txtWeight.setEnabled(true);

        int num = cmbChemType.getSelectedIndex();

        if (num == 1) {

            txtConcentration.setEnabled(false);
        } else if (num == 2) {

            txtWeight.setEnabled(false);
        } else if (num == 3) {
            txtConcentration.setEnabled(false);
            txtWeight.setEnabled(false);
        }
    }//GEN-LAST:event_cmbChemTypeMouseMoved

    private void tblChemicalDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChemicalDetailsMouseClicked

        int r1 = tblChemicalDetails.getSelectedRow();

        lblChemCode.setText(tblChemicalDetails.getValueAt(r1, 0).toString());
        txtChemName.setText(tblChemicalDetails.getValueAt(r1, 1).toString());
        cmbChemType.setSelectedItem(tblChemicalDetails.getValueAt(r1, 2).toString());
        if ((tblChemicalDetails.getValueAt(r1, 2).toString()).equals("Solid")) {
            txtWeight.setText(tblChemicalDetails.getValueAt(r1, 3).toString());
            txtConcentration.setEnabled(false);
        } else if ((tblChemicalDetails.getValueAt(r1, 2).toString()).equals("Hydraulic")) {
            txtConcentration.setText(tblChemicalDetails.getValueAt(r1, 3).toString());
            txtWeight.setEnabled(false);
        }
        lblSid.setText(tblChemicalDetails.getValueAt(r1, 4).toString());
        try {
            String sql = "select supName,brand from supplier where supId = '" + tblChemicalDetails.getValueAt(r1, 4).toString() + "'";
            p = c.prepareStatement(sql);
            rs = p.executeQuery();

            while (rs.next()) {
                String brand = rs.getString("brand");
                String name = rs.getString("supName");
                lblSname.setText(name);
                lblBrand.setText(brand);
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        txtPrice.setText(tblChemicalDetails.getValueAt(r1, 5).toString());
    }//GEN-LAST:event_tblChemicalDetailsMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String tchemCode = lblChemCode.getText();
        String tchemName = txtChemName.getText();
        String ttype = cmbChemType.getSelectedItem().toString();
        String tcon = txtConcentration.getText();
        String tweight = txtWeight.getText();
        String supId = lblSid.getText();
        double price = Double.parseDouble(txtPrice.getText());

        chemical_management a = new chemical_management();

        if (tchemCode.isEmpty() || tchemName.isEmpty() || ttype.isEmpty() || supId.isEmpty() | price ==0.0) {

            JOptionPane.showMessageDialog(this, "You Should Fill All Fields");
        } else if (!tcon.isEmpty()) {

            a.updateChemical(tchemCode, tchemName, ttype, tcon, supId,price);

            tableload();
            clearfield();

        } else if (!tweight.isEmpty()) {

            a.updateChemical(tchemCode, tchemName, ttype, tweight, supId,price);

            tableload();
            clearfield();
        }
        IncrementId mf = new IncrementId();
        String did = mf.setId("chemCode", "chemical", "CHEM");

        lblChemCode.setText(did);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtSnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSnameKeyReleased

        String sname = txtSname.getText();
        try {
            String ses = "SELECT supId as 'Supplier ID',supName as 'Supplier Name',brand as 'Company Name',email as 'Email' "
                    + "FROM supplier "
                    + "WHERE supName like '%" + sname + "%'or supId like '%" + sname + "%' or brand like '%" + sname + "%'";
            p = c.prepareStatement(ses);
            rs = p.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_txtSnameKeyReleased

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

        int r1 = jTable2.getSelectedRow();

        lblSid.setText(jTable2.getValueAt(r1, 0).toString());
        lblSname.setText(jTable2.getValueAt(r1, 1).toString());
        lblBrand.setText(jTable2.getValueAt(r1, 2).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String tchemCode = lblChemCode.getText();
        int y = JOptionPane.showConfirmDialog(this, "Do You Want to delete");

        if (y == 0) {

            chemical_management d = new chemical_management();
            d.deleteChemical(tchemCode);
            tableload();
            clearfield();
        }
        IncrementId mf = new IncrementId();
        String did = mf.setId("chemCode", "chemical", "CHEM");

        lblChemCode.setText(did);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbChemType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblChemCode;
    private javax.swing.JLabel lblSid;
    private javax.swing.JLabel lblSname;
    private javax.swing.JTable tblChemicalDetails;
    private javax.swing.JTextField txtChemName;
    private javax.swing.JTextField txtConcentration;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSname;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
