/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy_lab;

import code.DBconnection;
import code.IncrementId;
import code.lab_test_management;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Gayesha-PC
 */
public class Manage_Lab_Test extends javax.swing.JInternalFrame {

    Connection c = null;
    PreparedStatement p = null;
    ResultSet rs = null;

    public Manage_Lab_Test() {
        initComponents();
        c = DBconnection.getConnection();

        IncrementId mf = new IncrementId();
        String lid = mf.setId("testCode", "lab", "LAB");
        lblTestCode.setText(lid);
        ChemicalName();
        tableload();
    }

    public void tableload() {

        try {
            //String sql1 = "SELECT l.testCode as 'Lab Test Code',l.testName as 'Lab Test Name',l.testType as 'Test Type',l.discription as 'Discription' FROM lab l";
            String sql1 = "SELECT l.testCode as 'Lab Test Code',l.testName as 'Lab Test Name',l.testType as 'Test Type',l.discription as 'Discription',group_concat(c.chemName) as 'Chemicals'"
                    + " FROM lab l,chemical c,labchem lc "
                    + "where l.testCode=lc.testCode and lc.chemCode=c.chemCode and l.statua = 'NT' "
                    + "group by l.testCode";
            p = c.prepareStatement(sql1);
            rs = p.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }

    public void clearfield() {

        lblTestCode.setText("");
        txtTestType.setText("");
        txttestName.setText("");
        cmbChemicals.setSelectedIndex(0);
        txtDiscription.setText("");
    }

    public void ChemicalName() {
        try {
            String chemName = "SELECT chemName from chemical WHERE status = 'NT'";
            p = c.prepareStatement(chemName);
            rs = p.executeQuery();
            while (rs.next()) {
                String chem = rs.getString("chemName");
                cmbChemicals.addItem(chem);
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }

    public void clearTable(int row) {

        for (int i = 0; i < row; i++) {
            tblChemical.setValueAt("", i, 0);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiscription = new javax.swing.JTextArea();
        txtTestType = new javax.swing.JTextField();
        lblTestCode = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txttestName = new javax.swing.JTextField();
        cmbChemicals = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblChemical = new javax.swing.JTable();

        setTitle("Manage Lab Test Details");
        setPreferredSize(new java.awt.Dimension(1366, 550));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Lab Test Code", "Lab Test Name", "Test Type", "Description", "Chemicals"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lab Test Details"));

        jLabel2.setText("Lab Test Code");

        txtDiscription.setColumns(20);
        txtDiscription.setRows(5);
        jScrollPane1.setViewportView(txtDiscription);

        lblTestCode.setText("jLabel6");

        jLabel5.setText("Chemicals");

        jLabel3.setText("Test Type");

        jLabel4.setText("Description ");

        jLabel1.setText("Lab Test Name");

        cmbChemicals.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Chemical" }));
        cmbChemicals.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cmbChemicalsMouseMoved(evt);
            }
        });
        cmbChemicals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbChemicalsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmbChemicalsMousePressed(evt);
            }
        });
        cmbChemicals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbChemicalsActionPerformed(evt);
            }
        });

        tblChemical.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Chemicals"
            }
        ));
        jScrollPane3.setViewportView(tblChemical);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))
                            .addComponent(jLabel3))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtTestType)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 28, Short.MAX_VALUE))
                            .addComponent(cmbChemicals, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txttestName)
                            .addComponent(lblTestCode, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))))
                .addGap(0, 39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTestCode))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txttestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTestType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbChemicals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButton2)
                        .addGap(49, 49, 49)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(jButton3))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String ttestCode = lblTestCode.getText();
        String ttestsName = txttestName.getText();
        String ttestType = txtTestType.getText();
        String tdiscrption = txtDiscription.getText();
        String[] chemicals = new String[20];

        int filledRowCount = 0;
        rowSearch:
        for (int row = 0; row < tblChemical.getRowCount(); row++) {

            for (int col = 0; col < tblChemical.getColumnCount(); col++) {
                if (tblChemical.getValueAt(row, col) == null) {
                    break rowSearch;
                } else {
                    filledRowCount++;
                    continue rowSearch;
                }
            }
        }
        for (int i = 0; i < filledRowCount; i++) {
            chemicals[i] = tblChemical.getValueAt(i, 0).toString();
        }

        if (ttestCode.isEmpty() || ttestsName.isEmpty() || ttestType.isEmpty() || tdiscrption.isEmpty()) {

            JOptionPane.showMessageDialog(this, "You Should Fill All Fields");
        } else {
            lab_test_management a = new lab_test_management();
            a.addLabTest(ttestCode, ttestsName, ttestType, tdiscrption,chemicals);
            a.addLabTestChemecal(ttestCode, chemicals);
           /* try {

                String test = "INSERT INTO lab(testCode,testName,testType,discription,statua) values('" + ttestCode + "','" + ttestsName + "','" + ttestType + "','" + tdiscrption + "','NT')";
                p = c.prepareStatement(test);
                p.execute();

            } catch (SQLException ex) {
                System.out.println(ex);
            }

            try {
                for (int j = 0; j < chemicals.length; j++) {
                    String chem = "INSERT INTO labchem(testCode,chemCode) values('" + ttestCode + "',(select chemCode from chemical where chemName='" + chemicals[j] + "'))";
                    p = c.prepareStatement(chem);
                    p.execute();
                }
            } catch (SQLException ex) {
                System.out.println(ex);
            }*/
            tableload();
            clearfield();
            clearTable(filledRowCount);
            IncrementId mf = new IncrementId();
            String lid = mf.setId("testCode", "lab", "LAB");
            lblTestCode.setText(lid);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String ttestCode = lblTestCode.getText();
        String ttestsName = txttestName.getText();
        String ttestType = txtTestType.getText();
        String tdiscrption = txtDiscription.getText();
        String[] chemicals = new String[20];

        int filledRowCount = 0;
        rowSearch:
        for (int row = 0; row < tblChemical.getRowCount(); row++) {

            for (int col = 0; col < tblChemical.getColumnCount(); col++) {
                if (tblChemical.getValueAt(row, col) == null) {
                    break rowSearch;
                } else {
                    filledRowCount++;
                    continue rowSearch;
                }
            }
        }
        
        for (int i = 0; i < filledRowCount; i++) {
            chemicals[i] = tblChemical.getValueAt(i, 0).toString();
        }

        if (ttestCode.isEmpty() || ttestsName.isEmpty() || ttestType.isEmpty() || tdiscrption.isEmpty() || chemicals.length == 0) {

            JOptionPane.showMessageDialog(this, "You Should Fill All Fields");
        } else {
            lab_test_management up = new lab_test_management();
            
            try {
                up.updateLab(ttestCode, ttestsName, ttestType, tdiscrption,chemicals);
                up.updateLabChemicals(ttestCode, chemicals);
            } catch (SQLException ex) {
                System.out.println(ex);
            }
            tableload();
            clearfield();
            clearTable(filledRowCount);
        }
        IncrementId mf = new IncrementId();
        String lid = mf.setId("testCode", "lab", "LAB");
        lblTestCode.setText(lid);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String tlabCode = lblTestCode.getText();

        int y = JOptionPane.showConfirmDialog(this, "Do You Want to delete");

        if (y == 0) {

            lab_test_management d = new lab_test_management();
            d.deleteLab(tlabCode);
            tableload();
            clearfield();
        }
        IncrementId mf = new IncrementId();
        String lid = mf.setId("testCode", "lab", "LAB");
        lblTestCode.setText(lid);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

        int r1 = jTable2.getSelectedRow();

        txttestName.setText(jTable2.getValueAt(r1, 1).toString());
        lblTestCode.setText(jTable2.getValueAt(r1, 0).toString());
        txtTestType.setText(jTable2.getValueAt(r1, 2).toString());
        txtDiscription.setText(jTable2.getValueAt(r1, 3).toString());

        String chemicals = jTable2.getValueAt(r1, 4).toString();
        String data[] = chemicals.split(",");
        int count = data.length;

        for (int i = 0; i < count; i++) {
            tblChemical.setValueAt(data[i], i, 0);
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void cmbChemicalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbChemicalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbChemicalsActionPerformed

    private void cmbChemicalsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbChemicalsMouseMoved
        
        String chem = cmbChemicals.getSelectedItem().toString();

        int filledRowCount = 0;
        rowSearch:
        for (int row = 0; row < tblChemical.getRowCount(); row++) {

            for (int col = 0; col < tblChemical.getColumnCount(); col++) {
                if (tblChemical.getValueAt(row, col) == null) {
                    break rowSearch;
                } else {
                    filledRowCount++;
                    continue rowSearch;
                }
            }
        }

        if (filledRowCount == 0 && !chem.equals("Select Chemical")) {
            tblChemical.setValueAt(chem, 0, 0);
        } else {
            rowSearch2:
            for (int row = 0; row < filledRowCount; row++) {
                if (!(tblChemical.getValueAt(row, 0)).equals(chem) && row == filledRowCount - 1) {
                    tblChemical.setValueAt(chem, filledRowCount, 0);
                    break rowSearch2;
                } else {
                    continue rowSearch2;
                }

            }
        }
    }//GEN-LAST:event_cmbChemicalsMouseMoved

    private void cmbChemicalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbChemicalsMouseClicked

    }//GEN-LAST:event_cmbChemicalsMouseClicked

    private void cmbChemicalsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbChemicalsMousePressed
        
    }//GEN-LAST:event_cmbChemicalsMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbChemicals;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblTestCode;
    private javax.swing.JTable tblChemical;
    private javax.swing.JTextArea txtDiscription;
    private javax.swing.JTextField txtTestType;
    private javax.swing.JTextField txttestName;
    // End of variables declaration//GEN-END:variables
}
