/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy_lab;

import code.DBconnection;
import code.IncrementId;
import code.payment_management;
import code.validation;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Janaka Perera
 */
public class Payment_Order extends javax.swing.JInternalFrame {

    /**
     * Creates new form Payment_Order
     */
    Connection c = null;
    PreparedStatement p = null;
    ResultSet rs = null;
    public static boolean isbpres;
    //public static String usern = userName;

    public Payment_Order() {
        initComponents();
        c = DBconnection.getConnection();
        tableload();
        payments();
        IncrementId mf = new IncrementId();
        String did = mf.setId("idpayment", "payment", "PAY");

        lblPayID.setText(did);
    }

    public void tableload() {

        try {

            String sql = "SELECT supId as 'Supplier ID',supName as 'Supplier Name',brand as 'Company Name',email as 'Email'"
                    + " FROM supplier";
            p = c.prepareStatement(sql);
            rs = p.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this, "Cannot set to table");
        }

    }

    public void clearfield() {
        lblBalance.setText("");
        lblFamount.setText("");
        lblPayID.setText("");
        lblOid.setText("");
        lblSname.setText("");
        txtPayAmount.setText("");
    }

    public void payments() {
        try {
            String ms = "SELECT o.oid as 'Order ID',(o.amount-SUM(pay.orderPayAmount)) as 'Balance Amount',pay.orderPayAmount as 'Paid Amount',pay.date as 'Paid Date'\n"
                    + "FROM orders o,payment pay \n"
                    + "WHERE o.oid=pay.oid \n"
                    + "GROUP BY o.oid";
            p = c.prepareStatement(ms);
            rs = p.executeQuery();
            jTable2.setModel((TableModel) DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        txtSeSname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtSeBrand = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblPayID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblOid = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblFamount = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPayAmount = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lblSname = new javax.swing.JLabel();
        PayButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        NextButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setTitle("Order Payment");
        setMaximumSize(new java.awt.Dimension(1366, 550));
        setMinimumSize(new java.awt.Dimension(1366, 550));
        setPreferredSize(new java.awt.Dimension(1366, 550));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Serach Supplier By Name "));

        txtSeSname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSeSnameKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSeSname, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addGap(93, 93, 93))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSeSname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Supplier ID", "Supplier Name", "Company Name"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Payment ID", "Order ID", "Balance Amount", "Paid Amount", "Paid Date"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Brand By Name"));

        txtSeBrand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSeBrandKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSeBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSeBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Payment For Order"));

        jLabel1.setText("Payment ID");

        lblPayID.setText("Payment ID");

        jLabel3.setText("Order ID");

        lblOid.setText("Order ID");

        jLabel5.setText("Full Amount");

        lblFamount.setText("Full Amount");

        jLabel9.setText("Pay Amount");

        txtPayAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPayAmountActionPerformed(evt);
            }
        });

        jLabel10.setText("Supplier Name");

        lblSname.setText("Supplier Name");

        PayButton.setText("Pay");
        PayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Balance");

        lblBalance.setText("Balance");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5))
                    .addComponent(jLabel2)
                    .addComponent(jLabel9))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblPayID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblOid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFamount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPayAmount)
                        .addComponent(lblSname, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                    .addComponent(lblBalance))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PayButton)
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblPayID))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblOid))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblSname)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblFamount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblBalance))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPayAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(33, 33, 33)
                .addComponent(PayButton)
                .addGap(21, 21, 21))
        );

        NextButton.setText("Next");
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Payment Process");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 997, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NextButton)
                        .addGap(35, 35, 35)
                        .addComponent(BackButton)
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NextButton)
                                    .addComponent(BackButton))
                                .addGap(17, 17, 17)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Search By Brand");
        jPanel1.getAccessibleContext().setAccessibleDescription(jPanel1.getName());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSeSnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeSnameKeyReleased

        txtSeBrand.setEnabled(false);
        String sname = txtSeSname.getText();
        try {
            String ses = "SELECT supId as 'Supplier ID',supName as 'Supplier Name',brand as 'Company Name',email as 'Email'"
                    + " FROM supplier WHERE supName like '%" + sname + "%'";
            p = c.prepareStatement(ses);
            rs = p.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_txtSeSnameKeyReleased

    private void txtSeBrandKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeBrandKeyReleased

        txtSeSname.setEnabled(false);
        String brand = txtSeBrand.getText();
        try {
            String ses = "SELECT supId as 'Supplier ID',supName as 'Supplier Name',brand as 'Company Name',email as 'Email'"
                    + " FROM supplier WHERE brand like '%" + brand + "%'";
            p = c.prepareStatement(ses);
            rs = p.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            System.out.println(ex);

        }
    }//GEN-LAST:event_txtSeBrandKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        if (isbpres == true) {

            int rj = jTable1.getSelectedRow();

            lblOid.setText(jTable1.getValueAt(rj, 0).toString());
            lblFamount.setText(jTable1.getValueAt(rj, 2).toString());
            String oid = jTable1.getValueAt(rj, 0).toString();
            String sname = null;

            try {
                String s = "SELECT s.supName \n"
                        + "FROM supplier s,orders o\n"
                        + "WHERE s.supId = o.supId AND o.oid='" + oid + "'";
                p = c.prepareStatement(s);
                rs = p.executeQuery();

                while (rs.next()) {
                    sname = rs.getString("supName");
                }
                lblSname.setText(sname);
            } catch (SQLException ex) {
                Logger.getLogger(Payment_Order.class.getName()).log(Level.SEVERE, null, ex);
            }

            double full = Double.parseDouble(jTable1.getValueAt(rj, 2).toString());
            double paid = 0;
            double fpaid = 0;

            try {
                String paidq = "SELECT orderPayAmount "
                        + "FROM payment  "
                        + "Where oid='" + oid + "'";
                p = c.prepareStatement(paidq);
                rs = p.executeQuery();

                while (rs.next()) {

                    paid = Double.parseDouble(rs.getString("orderPayAmount"));
                    fpaid = fpaid + paid;

                }
            } catch (SQLException ex) {
                Logger.getLogger(Payment_Order.class.getName()).log(Level.SEVERE, null, ex);
            }

            double balance = full - fpaid;

            lblFamount.setText("" + full);
            lblBalance.setText("" + balance);

            /*  try {
                String ms = "SELECT pay.idpayment as 'Payment ID',o.idsup_order as 'Order ID',pay.orderPayAmount as 'Paid Amount',pay.date as 'Paid Date'"
                        + " FROM sup_order o,order sop,payment pay "
                        + "WHERE sop.idsup_order_product='" + oid + "' AND sop.idsup_order_product=o.idsup_order AND sop.idsup_order_product=pay.oid "
                        + "GROUP BY pay.idpayment,o.idsup_order";
                p = c.prepareStatement(ms);
                rs = p.executeQuery();
                jTable2.setModel((TableModel) DbUtils.resultSetToTableModel(rs));

            } catch (Exception e) {
                System.out.println(e);
            }*/
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtPayAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPayAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPayAmountActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

       
    }//GEN-LAST:event_jTable2MouseClicked

    private void PayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayButtonActionPerformed

        String tpayid = lblPayID.getText();
        String oid = lblOid.getText();
        String orPayAmount = txtPayAmount.getText();
        String balance = lblBalance.getText();

        validation vi = new validation();
        
        payment_management ap = new payment_management();

        if (orPayAmount.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pleace fill the pay amount field ");
        } else if (vi.priceOnly(orPayAmount)) {
            if (Double.parseDouble(orPayAmount) >= Double.parseDouble(balance)) {
                
                ap.addPaymentFull(tpayid, oid, orPayAmount);
                
            } else if (Double.parseDouble(orPayAmount) < Double.parseDouble(balance)) {

                ap.addPaymentHalf(tpayid, oid, orPayAmount);
            }
            payments();
            clearfield();
            IncrementId mf = new IncrementId();
            String did = mf.setId("idpayment", "payment", "PAY");

            lblPayID.setText(did);

        } else {
            JOptionPane.showMessageDialog(this, "Price should have [0-9] digits and one dot only");
        }
    }//GEN-LAST:event_PayButtonActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed

        int r = jTable1.getSelectedRow();
        String sid = jTable1.getValueAt(r, 0).toString();

        try {
            String sql = "SELECT so.oid as 'Order ID',so.date as 'Order Date',so.amount as 'Full Amount' "
                    + "FROM orders so "
                    + "WHERE so.supId='" + sid + "' and so.order_status = 'done' and so.payment_status != 'done' "
                    + "GROUP BY so.oid,so.date";
            p = c.prepareStatement(sql);
            rs = p.executeQuery();
            jTable1.setModel((TableModel) DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(Payment_Order.class.getName()).log(Level.SEVERE, null, ex);
        }

        isbpres = true;
    }//GEN-LAST:event_NextButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed

        tableload();

        txtSeSname.setText("");
        txtSeBrand.setText("");
        txtSeBrand.setEnabled(true);
        txtSeSname.setEnabled(true);
        lblOid.setText("Order ID");
        lblSname.setText("Supplier Name");
        lblFamount.setText("Full Amount");
        lblBalance.setText("Balance");

        isbpres = false;
    }//GEN-LAST:event_BackButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int r = jTable2.getSelectedRow();
        String oid = jTable2.getValueAt(r, 0).toString();

        try {
            String sql = "SELECT p.idpayment as 'Payment ID',p.date as 'Payment Date',p.orderPayAmount as 'Paid Amount' "
                    + "FROM payment p "
                    + "WHERE p.oid='" + oid + "' ";
            p = c.prepareStatement(sql);
            rs = p.executeQuery();
            jTable2.setModel((TableModel) DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(Payment_Order.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton NextButton;
    private javax.swing.JButton PayButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblFamount;
    private javax.swing.JLabel lblOid;
    private javax.swing.JLabel lblPayID;
    private javax.swing.JLabel lblSname;
    private javax.swing.JTextField txtPayAmount;
    private javax.swing.JTextField txtSeBrand;
    private javax.swing.JTextField txtSeSname;
    // End of variables declaration//GEN-END:variables
}
